version: "3"
services: 
    api:
        build: .
        depends_on:
            - postgres
        ports: 
            - 8000:8000
        volumes:
            - ./:/usr/src/app
        command: uvicorn app.main:app --host localhost --port 8000 --reload
        #env_file:
        #    - ./.env
        environment: 
            - DATABASE_HOSTNAME=postgres
            - DATABASE_PORT=5432
            - DATABASE_PASSWORD=rong5807*
            - DATABASE_NAME=fastapi
            - DATABASE_USERNAME=postgres
            - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4rongcaa6cf63b88e8d3e7
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=60

    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=rong5807*
            - POSTGRES_DB=fastapi

        volumes:
            - postgres-db:/var/lib/postgres/data

volumes:
    postgres-db:

