version: "3"
services: 
    api:
        image: intrinsicvalue01/fastapi
        depends_on:
            - postgres
        ports: 
            - 80:8000
        # command: uvicorn app.main:app --host localhost --port 8000
        # env_file:
        #    - ./.env
        environment: 
            - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USERNAME=${DATABASE_USERNAME}
            - SECRET_KEY=${SECRET_KEY}
            - ALGORITHM=${ALGORITHM}
            - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_DB}

        volumes:
            - postgres-db:/var/lib/postgres/data

volumes:
    postgres-db:

